### ISSUE TITLE
how to use dask for function threshold? i have big grid data

### ISSUE THREAD

**Issue by liuh1995** [coecms/xmhw#68]

**Comment by paolap** [comment]
Dask is already used under the hood (see documentation), but you would have to start up a dask client to allow the code to work in parallel properly. I'm going to close this as this is not an issue with the code itself.

**Comment by liuh1995** [comment]
Can you give me an example, thanks!

**Comment by paolap** [comment]
I'm sorry I don't have time to setup an example plus dask depends a lot on the data you're trying to process, as I said there's some explanations in the documentation.

**Comment by liuh1995** [comment]
thanks! 
![image](https://github.com/coecms/xmhw/assets/53523867/e1499143-a8f5-44e7-a66e-d9b75cadd0a2)
I found your example, but where are the variables "thresh and seas"  found in the graph, because my data is 11GB, which is slow to run when using threshold directly.
